cmd_/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o := arm-cortex_a9-linux-gnueabi-gcc -Wp,-MD,/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/.fic.o.d  -nostdinc -isystem /opt/crosstools/arm-cortex_a9-eabi-4.7-eglibc-2.18/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-s5p4418/include -Iarch/arm/plat-s5p4418/include -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/plat-s5p4418/common -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/plat-s5p4418/iA1/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/mach-s5p4418/prototype/base -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/mach-s5p4418/prototype/module -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/mach-s5p4418/prototype/module -D__LINUX__ -D__PRINTK__ -DNX_RELEASE -mtune=cortex-a9 -mfpu=vfp -mfloat-abi=softfp -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/plat-s5p4418/common -I/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/kernel/kernel-3.4.39/arch/arm/plat-s5p4418/iA1/include -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I./include  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(fic)"  -D"KBUILD_MODNAME=KBUILD_STR(fc8080_tpeg)" -c -o /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.c

source_/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o := /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.c

deps_/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o := \
  /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/../include/fic.h \
  /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/../include/ficdecoder.h \
  /home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/../include/fci_types.h \

/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o: $(deps_/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o)

$(deps_/home/appsw4/work/Customers/IA-INC/iA1/linux-IAHD/platform/s5p4418/modules/fc8080_tpeg/src/fic.o):
