#!/bin/sh

while true
do
	if grep -qs "mmcblk0p1" /proc/mounts; then
		break
	fi
done

export PATH=$PATH:/mnt/mmc/bin
export LD_LIBRARY_PATH=/mnt/mmc/lib

cd /mnt/mmc/bin/cert
ruby make-dc-certificate-chain.rb

cd /mnt/mmc/bin
./sap_slink_client &
